spring:
  application:
    name: alertly
  datasource:
    url: jdbc:postgresql://localhost:5434/db
    username: postgres
    password: 1112
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port: 19014
alertly:
  default-user-settings:
    radius: 10
    category:
      - OTHER
      - FIGHT
      - SUSPICIOUS
    level:
      - LOW
      - MEDIUM
      - HIGH
