spring:
  application:
    name: alertly
  datasource:
    url: jdbc:postgresql://localhost:5434/db
    username: postgres
    password: 1112
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alertly-consumer
      auto-offset-reset: earliest
    topic:
      alert: alert
server:
  port: 19014
alertly:
  default-user-settings:
    close-incident-distance: 200
    radius: 10
    category:
      - OTHER
      - FIGHT
      - SUSPICIOUS
    level:
      - LOW
      - MEDIUM
      - HIGH